// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0CP50eLjPeOJrm4Pw8izX8DXSbJQAhCs',
    appId: '1:219114146140:web:4c099606f80d180744d999',
    messagingSenderId: '219114146140',
    projectId: 'signlog-fc5f3',
    authDomain: 'signlog-fc5f3.firebaseapp.com',
    storageBucket: 'signlog-fc5f3.firebasestorage.app',
    measurementId: 'G-9H9FP39JSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBds39Nl38yzpL972WTPGPkfXREWWabpJU',
    appId: '1:219114146140:android:ae4369e9e3d9354044d999',
    messagingSenderId: '219114146140',
    projectId: 'signlog-fc5f3',
    storageBucket: 'signlog-fc5f3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0CP50eLjPeOJrm4Pw8izX8DXSbJQAhCs',
    appId: '1:219114146140:web:3a672ce0a82e823344d999',
    messagingSenderId: '219114146140',
    projectId: 'signlog-fc5f3',
    authDomain: 'signlog-fc5f3.firebaseapp.com',
    storageBucket: 'signlog-fc5f3.firebasestorage.app',
    measurementId: 'G-L7KZN1FSTX',
  );
}
